name: Terraform CI-CD

on:
  push:
    branches:
      - "**"

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: "de1ced98-6870-4b38-9d44-2d879b01b1b0"
  ARM_TENANT_ID: "44ff9492-6357-4790-9759-8d5b4666c643"
  ARM_SUBSCRIPTION_ID: "f506e9ea-7a47-4c62-82ac-24efcf83b366"

jobs:

  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Env/prod

    steps:

      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: "de1ced98-6870-4b38-9d44-2d879b01b1b0"
          tenant-id: "44ff9492-6357-4790-9759-8d5b4666c643"
          subscription-id:  "f506e9ea-7a47-4c62-82ac-24efcf83b366"

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 5. Terraform Format
      - name: Terraform Format
        run: terraform fmt -recursive

      # 6. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 7. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 8. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan